import { writeFileSync, readFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname, basename } from "path";
import type { ParsedModule, DocSnapshot } from "../types.ts";
import { generateMarkdown } from "./llm.ts";
import { buildModulePrompt, buildIndexPrompt } from "./render.ts";

const SNAPSHOT_FILE = "docsbot-snapshot.json";

function loadSnapshot(outputDir: string): DocSnapshot {
  const path = join(outputDir, SNAPSHOT_FILE);
  if (!existsSync(path)) return { generatedAt: "", modules: {} };
  return JSON.parse(readFileSync(path, "utf8"));
}

function saveSnapshot(outputDir: string, snapshot: DocSnapshot): void {
  const path = join(outputDir, SNAPSHOT_FILE);
  writeFileSync(path, JSON.stringify(snapshot, null, 2));
}

function docPath(outputDir: string, moduleId: string): string {
  // src/api/store.ts → agent/src/api/store.md
  const withoutExt = moduleId.replace(/\.tsx?$/, "");
  return join(outputDir, `${withoutExt}.md`);
}

/**
 * Generate agent docs for all parsed modules.
 * Only re-generates docs for modules whose content hash changed.
 *
 * @param modules Parsed source modules
 * @param outputDir Directory to write .md files into
 * @param force Re-generate all docs even if hashes match
 * @param headCommit Current HEAD commit SHA — stored in snapshot for incremental runs
 */
export async function generateAgentDocs(
  modules: ParsedModule[],
  outputDir: string,
  force = false,
  headCommit?: string
): Promise<{ generated: string[]; skipped: string[] }> {
  const snapshot = loadSnapshot(outputDir);
  const generated: string[] = [];
  const skipped: string[] = [];

  for (const mod of modules) {
    const prev = snapshot.modules[mod.moduleId];
    const outPath = docPath(outputDir, mod.moduleId);

    if (!force && prev?.contentHash === mod.contentHash && existsSync(outPath)) {
      skipped.push(mod.moduleId);
      continue;
    }

    // Skip files with nothing to document
    if (
      mod.functions.length === 0 &&
      mod.types.length === 0 &&
      mod.classes.length === 0
    ) {
      skipped.push(mod.moduleId);
      continue;
    }

    console.log(`  generating docs: ${mod.moduleId}`);
    const prompt = buildModulePrompt(mod);
    const markdown = await generateMarkdown(prompt);

    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, `<!-- generated by docsbot — do not edit manually -->\n\n${markdown}\n`);

    snapshot.modules[mod.moduleId] = {
      contentHash: mod.contentHash,
      docPath: outPath,
    };
    generated.push(mod.moduleId);
  }

  // Generate index
  const allModules = modules
    .filter(
      (m) =>
        m.functions.length > 0 || m.types.length > 0 || m.classes.length > 0
    )
    .map((m) => m.moduleId);

  if (allModules.length > 0) {
    const indexPath = join(outputDir, "index.md");
    const shouldRegen =
      force || generated.length > 0 || !existsSync(indexPath);
    if (shouldRegen) {
      console.log("  generating index…");
      const indexMd = await generateMarkdown(buildIndexPrompt(allModules));
      writeFileSync(
        indexPath,
        `<!-- generated by docsbot — do not edit manually -->\n\n${indexMd}\n`
      );
    }
  }

  snapshot.generatedAt = new Date().toISOString();
  if (headCommit) snapshot.lastCommit = headCommit;
  saveSnapshot(outputDir, snapshot);

  return { generated, skipped };
}
